# Supports Linux pkg-config and a Windows SDK containing include/, lib/, bin/.
set(FFMPEG_ROOT "" CACHE PATH "FFmpeg development SDK root (matching compiler/architecture)")
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_check_modules(PC_FFMPEG QUIET libavformat libavcodec libavutil)
endif()
find_path(FFMPEG_INCLUDE_DIR libavformat/avformat.h HINTS "${FFMPEG_ROOT}/include" ${PC_FFMPEG_INCLUDE_DIRS})
foreach(component avformat avcodec avutil)
    find_library(FFMPEG_${component}_LIBRARY NAMES ${component} HINTS "${FFMPEG_ROOT}/lib" ${PC_FFMPEG_LIBRARY_DIRS})
endforeach()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFmpeg REQUIRED_VARS FFMPEG_INCLUDE_DIR FFMPEG_avformat_LIBRARY FFMPEG_avcodec_LIBRARY FFMPEG_avutil_LIBRARY)
if(FFmpeg_FOUND AND NOT TARGET FFmpeg::FFmpeg)
    add_library(FFmpeg::FFmpeg INTERFACE IMPORTED)
    set_target_properties(FFmpeg::FFmpeg PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${FFMPEG_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES "${FFMPEG_avformat_LIBRARY};${FFMPEG_avcodec_LIBRARY};${FFMPEG_avutil_LIBRARY}")
endif()
